/**
 * MYRAA — Security + Intelligence Separation Types (Phase 26)
 *
 * Establishes absolute architectural and operational boundaries between
 * AI Reasoning (Intelligence/Multi-Agent/Coder/Planner/Proactive/Recovery)
 * and Security Authority (Policy, Risk, RBAC, Firewall, Emergency Stop, Lockdown).
 *
 * Core Axiom:
 *   AI Brain = PROPOSE ONLY
 *   Security Layer = AUTHORITATIVE EVALUATION & GATEKEEPING
 *   Executor = EXECUTION ONLY UPON CRYPTOGRAPHICALLY VERIFIED SECURITY DECISION
 */

import type { RiskLevel, SecurityMode, SecurityContext } from "../SecurityTypes.ts";

/**
 * Originating source of an AI action proposal.
 */
export type ProposalSource =
  | "PLANNER"
  | "CODER"
  | "RESEARCHER"
  | "PROACTIVE"
  | "RECOVERY"
  | "USER_CHAT"
  | "CRITIC"
  | "VERIFIER"
  | "UNKNOWN";

/**
 * Untrusted action proposal generated by an AI reasoning component.
 * Contains ZERO authoritative permissions.
 */
export interface AIActionProposal {
  readonly proposalId: string;
  readonly source: ProposalSource;
  readonly toolName: string;
  readonly args: Record<string, unknown>;
  readonly intentDescription: string;
  readonly requestedScope?: string[];
  /** Advisory only. Ignored by SecurityAuthority during authoritative risk assessment. */
  readonly riskHint?: string;
  readonly modelMetadata?: {
    model?: string;
    agentRole?: string;
    confidence?: number;
    promptContext?: string;
  };
  readonly createdAt: number;
  readonly nonce: string;
}

/**
 * Decision outcome issued strictly by SecurityAuthority.
 */
export type DecisionOutcome = "ALLOW" | "REQUIRE_CONFIRMATION" | "BLOCK";

/**
 * Cryptographically signed, authoritative security decision.
 * Only the SecurityAuthority can issue this. AI can never forge or create it.
 */
export interface SecurityDecision {
  readonly decisionId: string;
  readonly proposalId: string;
  readonly toolName: string;
  readonly decision: DecisionOutcome;
  readonly allowed: boolean;
  readonly riskLevel: RiskLevel;
  readonly riskScore: number;
  readonly reasons: readonly string[];
  readonly requiresConfirmation: boolean;
  readonly confirmationToken?: string;
  /** SHA-256 fingerprint binding proposalId, toolName, canonical args, riskLevel, issuedAt. */
  readonly fingerprint: string;
  /** HMAC-SHA256 signature produced using POLICY_SIGNING_SECRET. */
  readonly signature: string;
  readonly issuedAt: number;
  readonly expiresAt: number;
  readonly authorizedBy:
    | "SECURITY_POLICY_ENGINE"
    | "EMERGENCY_STOP"
    | "LOCKDOWN_POLICY"
    | "SECURITY_AUTHORITY";
  readonly requestedScope?: readonly string[];
  readonly consumed: boolean;
  readonly consumedAt?: number;
}

/**
 * Classifies security trust boundary violation types.
 */
export type BoundaryViolationType =
  | "PROPOSAL_FORGERY"
  | "DECISION_FORGERY"
  | "ARGUMENT_TAMPER"
  | "SCOPE_EXPANSION"
  | "EXPIRED_DECISION"
  | "REPLAY_ATTACK"
  | "UNAUTHORIZED_EXECUTION"
  | "PRIVILEGE_ESCALATION"
  | "EMERGENCY_STOP_ACTIVE"
  | "LOCKDOWN_ACTIVE"
  | "DISALLOWED_TOOL"
  | "MALICIOUS_INJECTION"
  | "CONFIRMATION_MISSING";

/**
 * Structured violation event.
 */
export interface BoundaryViolation {
  readonly type: BoundaryViolationType;
  readonly message: string;
  readonly proposalId?: string;
  readonly decisionId?: string;
  readonly toolName?: string;
  readonly timestamp: number;
  readonly details?: Record<string, unknown>;
}

/**
 * Result of validating a decision prior to execution.
 */
export interface DecisionValidationResult {
  readonly valid: boolean;
  readonly violation?: BoundaryViolation;
  readonly decision?: SecurityDecision;
}

/**
 * Result of guarded execution via SecurityExecutionAdapter.
 */
export interface SeparationExecutionResult {
  readonly success: boolean;
  readonly proposalId: string;
  readonly decisionId: string;
  readonly toolName: string;
  readonly result?: unknown;
  readonly error?: string;
  readonly executionTimeMs: number;
  readonly blocked: boolean;
  readonly violation?: BoundaryViolation;
}

/**
 * Full audit record documenting the proposal -> evaluation -> validation -> execution pipeline.
 */
export interface SeparationAuditRecord {
  readonly auditId: string;
  readonly timestamp: number;
  readonly proposal: AIActionProposal;
  readonly decision: SecurityDecision;
  readonly executionResult?: SeparationExecutionResult;
  readonly violation?: BoundaryViolation;
  readonly context: SecurityContext;
}

/**
 * Options for proposing an AI action.
 */
export interface ProposeActionOptions {
  source: ProposalSource;
  toolName: string;
  args: Record<string, unknown>;
  intentDescription: string;
  requestedScope?: string[];
  riskHint?: string;
  modelMetadata?: {
    model?: string;
    agentRole?: string;
    confidence?: number;
    promptContext?: string;
  };
}

/**
 * System status for Security Separation.
 */
export interface SecuritySeparationStatus {
  readonly initialized: boolean;
  readonly activeMode: SecurityMode;
  readonly emergencyStopActive: boolean;
  readonly totalProposalsProcessed: number;
  readonly totalDecisionsIssued: number;
  readonly totalExecutionsCompleted: number;
  readonly totalViolationsDetected: number;
  readonly activeDecisionsCount: number;
  readonly consumedDecisionsCount: number;
}
