@echo off
rem ==============================================================================
rem MYRAA Android Companion — Development/Staging Release Keystore Generator
rem Phase 30 — Production Hardening & Release Readiness
rem
rem NOTICE:
rem This script is for LOCAL DEVELOPMENT / STAGING testing only.
rem The keystore generated by this script is NOT your Google Play Store production key.
rem
rem Play Store Production Signing Workflow:
rem   1. Generate or import official organization release key into secure secret store (e.g. CI/CD KMS).
rem   2. Set MYRAA_RELEASE_KEYSTORE_PATH and MYRAA_RELEASE_STORE_PASSWORD as CI secrets.
rem   3. Sign Android App Bundle (AAB).
rem   4. Upload to Google Play Console with Play App Signing.
rem ==============================================================================

setlocal enabledelayedexpansion

set KEYSTORE_NAME=release-keystore.jks
set KEY_ALIAS=myraa_release_key
set JBR_KEYTOOL="C:\Program Files\Android\Android Studio\jbr\bin\keytool.exe"

if exist "%JBR_KEYTOOL%" (
    set KEYTOOL_CMD=%JBR_KEYTOOL%
) else (
    set KEYTOOL_CMD=keytool
)

echo [MYRAA KeyGen] Generating staging release keystore: %KEYSTORE_NAME%...

if exist "%KEYSTORE_NAME%" (
    echo [MYRAA KeyGen] Keystore %KEYSTORE_NAME% already exists in current directory.
    goto end
)

rem Default development/staging password — override with environment or prompt
if "%MYRAA_STAGING_PASSWORD%"=="" (
    set STORE_PASS=MyraaReleaseStagingPass2026!
) else (
    set STORE_PASS=%MYRAA_STAGING_PASSWORD%
)

%KEYTOOL_CMD% -genkeypair -v ^
  -keystore "%KEYSTORE_NAME%" ^
  -alias "%KEY_ALIAS%" ^
  -keyalg RSA ^
  -keysize 2048 ^
  -validity 10000 ^
  -storetype PKCS12 ^
  -storepass "%STORE_PASS%" ^
  -keypass "%STORE_PASS%" ^
  -dname "CN=MYRAA Companion Staging, OU=Engineering, O=MYRAA, L=Bengaluru, ST=Karnataka, C=IN"

if %ERRORLEVEL% EQU 0 (
    echo [MYRAA KeyGen] Staging release keystore created successfully: %KEYSTORE_NAME%
    echo [MYRAA KeyGen] Keystore path: %~dp0%KEYSTORE_NAME%
    echo [MYRAA KeyGen] Note: Keystore files are ignored by git (.gitignore) to prevent credential leakage.
) else (
    echo [MYRAA KeyGen] Error generating keystore. Exit code: %ERRORLEVEL%
)

:end
endlocal
