<#
.SYNOPSIS
    MYRAA Android Companion — Development/Staging Release Keystore Generator
    Phase 30 — Production Hardening & Release Readiness

.DESCRIPTION
    NOTICE:
    This script is for LOCAL DEVELOPMENT / STAGING testing only.
    The keystore generated by this script is NOT your Google Play Store production key.

    Play Store Production Signing Workflow:
      1. Generate or import official organization release key into secure secret store (e.g. CI/CD KMS).
      2. Set MYRAA_RELEASE_KEYSTORE_PATH and MYRAA_RELEASE_STORE_PASSWORD as CI secrets.
      3. Sign Android App Bundle (AAB).
      4. Upload to Google Play Console with Play App Signing.
#>

$KeystoreName = "release-keystore.jks"
$KeyAlias = "myraa_release_key"
$KeytoolPath = "C:\Program Files\Android\Android Studio\jbr\bin\keytool.exe"

if (-not (Test-Path $KeytoolPath)) {
    $KeytoolPath = "keytool"
}

if (Test-Path $KeystoreName) {
    Write-Host "[MYRAA KeyGen] Keystore '$KeystoreName' already exists in current directory."
    exit 0
}

$StorePass = if ($env:MYRAA_STAGING_PASSWORD) { $env:MYRAA_STAGING_PASSWORD } else { "MyraaReleaseStagingPass2026!" }

Write-Host "[MYRAA KeyGen] Generating staging release keystore: $KeystoreName..."

& $KeytoolPath -genkeypair -v `
  -keystore $KeystoreName `
  -alias $KeyAlias `
  -keyalg RSA `
  -keysize 2048 `
  -validity 10000 `
  -storetype PKCS12 `
  -storepass $StorePass `
  -keypass $StorePass `
  -dname "CN=MYRAA Companion Staging, OU=Engineering, O=MYRAA, L=Bengaluru, ST=Karnataka, C=IN"

if ($LASTEXITCODE -eq 0) {
    Write-Host "[MYRAA KeyGen] Staging release keystore created successfully: $KeystoreName"
    Write-Host "[MYRAA KeyGen] Note: Keystores are excluded in .gitignore to prevent credential leakage."
} else {
    Write-Error "[MYRAA KeyGen] Failed to generate keystore. Exit code: $LASTEXITCODE"
}
