/**
 * MYRAA — Phase 2 Advanced Memory Types
 *
 * EnhancedMemory extends the existing Memory interface with optional metadata
 * fields. All new fields have defaults so existing memories.json records load
 * without migration: MemoryStore.load() transparently fills in defaults.
 *
 * This file contains ONLY type/interface definitions — no runtime logic.
 */

import type { Memory, MemoryCategory } from "../../lib/memoryTypes.ts";

// ---------------------------------------------------------------------------
// Scalar value types
// ---------------------------------------------------------------------------

/** Relative importance of a memory for context retrieval ranking. */
export type Importance = "low" | "medium" | "high";

/** Confidence that the memory fact is accurate. */
export type Confidence = "low" | "medium" | "high";

/**
 * How this memory was created / verified.
 *   user_explicit       — user directly stated it in conversation
 *   conversation_extracted — Gemini model extracted it during background consolidation
 *   user_confirmed      — user confirmed a previously-extracted fact
 *   system_generated    — created via POST /api/memories or saveCustomMemory tool
 *   imported            — loaded from an external source
 */
export type MemorySource =
  | "user_explicit"
  | "conversation_extracted"
  | "user_confirmed"
  | "system_generated"
  | "imported";

/**
 * Lifecycle status.
 *   active              — normal retrieval and context injection
 *   archived            — kept on disk, excluded from retrieval
 *   needs_revalidation  — still retrievable but flagged for user/AI review
 */
export type MemoryStatus = "active" | "archived" | "needs_revalidation";

// ---------------------------------------------------------------------------
// Enhanced memory record
// ---------------------------------------------------------------------------

/**
 * EnhancedMemory is a strict superset of Memory.
 * All new fields are optional-on-disk; MemoryStore adds defaults on load so
 * code that reads this type can always rely on importance/confidence/source/status.
 */
export interface EnhancedMemory extends Memory {
  /**
   * Short slug used as deduplication anchor (e.g. "favorite_food").
   * If two memories share the same non-empty key and category, the second is
   * treated as an update candidate rather than a new record.
   */
  key?: string;

  /** Relative importance for context ranking. Default: "medium". */
  importance: Importance;

  /** Confidence in the accuracy of this fact. Default: "medium". */
  confidence: Confidence;

  /** How this memory was created. Default: "conversation_extracted". */
  source: MemorySource;

  /** ISO8601 timestamp of the most recent context retrieval. */
  lastAccessedAt?: string;

  /**
   * ISO8601 timestamp after which this memory must not be retrieved.
   * Absent (undefined) means the memory is permanent.
   * Only set when a memory is explicitly temporary or when a documented rule
   * applies (see MemoryStore.shouldExpire).
   */
  expiresAt?: string;

  /** Lifecycle status. Default: "active". */
  status: MemoryStatus;

  /** Originating or last-modifying device ID. */
  deviceId?: string;

  /** Originating or last-modifying device type. Default: "desktop". */
  deviceType?: "desktop" | "android" | "system";

  /** Monotonic record version for deterministic conflict resolution (>= 1). */
  version?: number;

  /** Timestamp of the most recent cross-device synchronization. */
  lastSyncedAt?: string;

  /** Optional client mutation ID for idempotent offline synchronization. */
  clientMutationId?: string;
}

// ---------------------------------------------------------------------------
// Shared Memory & Synchronization Types (Phase 24)
// ---------------------------------------------------------------------------

export type DeviceType = "desktop" | "android" | "system";

export type MemoryMutationType = "CREATE" | "UPDATE" | "DELETE";

export interface MemorySyncMutation {
  /** Unique mutation identifier generated by client for idempotency. */
  clientMutationId: string;
  /** Operation type to perform. */
  mutationType: MemoryMutationType;
  /** Target memory ID (required for UPDATE and DELETE). */
  memoryId?: string;
  /** Mutation payload for CREATE or UPDATE. */
  data?: {
    category?: MemoryCategory;
    text?: string;
    key?: string;
    importance?: Importance;
    confidence?: Confidence;
    source?: MemorySource;
    expiresAt?: string;
    status?: MemoryStatus;
  };
  /** Client-side ISO8601 mutation timestamp. */
  timestamp: string;
  /** Base version known to client at mutation creation (for optimistic concurrency). */
  clientVersion?: number;
}

export interface MemorySyncBatchRequest {
  deviceId: string;
  deviceType: "desktop" | "android";
  mutations: MemorySyncMutation[];
  lastSyncTimestamp?: string;
}

export interface MemorySyncBatchResponse {
  success: boolean;
  appliedCount: number;
  conflictsResolved: number;
  memories: EnhancedMemory[];
  serverTimestamp: string;
  rejectedMutations?: Array<{
    clientMutationId: string;
    reason: string;
    memoryId?: string;
  }>;
}

export interface SharedMemorySyncEvent {
  type: "memory_sync" | "shared_memory_event";
  action: "create" | "update" | "delete" | "batch_sync";
  deviceId: string;
  deviceType: DeviceType;
  memoryId?: string;
  memories: EnhancedMemory[];
  timestamp: string;
  version?: number;
}

export interface SharedMemoryOperationResult {
  success: boolean;
  memory?: EnhancedMemory;
  error?: string;
  conflictResolved?: boolean;
  resolutionNote?: string;
}

// ---------------------------------------------------------------------------
// Operation options
// ---------------------------------------------------------------------------

/** Options for MemoryManager.searchMemories(). */
export interface MemorySearchOptions {
  /** Free-text keyword search across text, key, category. */
  query?: string;
  /** Filter to one or more categories. */
  categories?: MemoryCategory[];
  /** Only return memories with this minimum importance. */
  minImportance?: Importance;
  /** Only return memories with this minimum confidence. */
  minConfidence?: Confidence;
  /** Only return memories with this source. */
  source?: MemorySource;
  /** Maximum number of results. Default: 20. */
  limit?: number;
  /** Include archived memories. Default: false. */
  includeArchived?: boolean;
  /** Include needs_revalidation memories. Default: true. */
  includeNeedsRevalidation?: boolean;
}

/** Options for MemoryManager.getRelevantContext(). */
export interface ContextOptions {
  /**
   * Free-text query hint for ranking (e.g. the current user turn).
   * When provided, memories whose text contains query words score higher.
   */
  query?: string;
  /**
   * Maximum total characters to include in the injected memory block.
   * Never exceeded. Default: 2000.
   */
  contextCharBudget?: number;
  /** Update lastAccessedAt for each retrieved memory. Default: true. */
  touchLastAccessed?: boolean;
}

// ---------------------------------------------------------------------------
// Deduplication result
// ---------------------------------------------------------------------------

export type DeduplicationMatch = "exact" | "similar" | "conflict" | "none";

export interface DeduplicationResult {
  match: DeduplicationMatch;
  /** The existing memory that matched (undefined when match === "none"). */
  existing?: EnhancedMemory;
  /** Similarity score 0–1 (Jaccard word-level). */
  score: number;
}

// Re-export base types for convenience
export type { Memory, MemoryCategory };
