/**
 * MYRAA — MemoryExtractor
 *
 * Wraps the existing processConversationSlice() from server_memory.ts and adds:
 *   1. Deduplication — checks each ADD transaction against existing memories
 *      before creating a new record, applying merge/update/conflict logic.
 *   2. EnhancedMemory output — all created/updated records include the new
 *      Phase 2 fields (importance, confidence, source, status).
 *
 * GeminiSessionFactory should call extractAndApply() instead of
 * processConversationSlice() directly. The legacy function remains in
 * server_memory.ts for backward compatibility.
 */

import { processConversationSlice } from "../../../server_memory.ts";
import { MemoryStore, memoryStore } from "./MemoryStore.ts";
import { findSimilar, mergeText } from "./MemoryDeduplicator.ts";
import type { EnhancedMemory, MemorySource } from "./MemoryTypes.ts";
import type { MemoryCategory } from "../../lib/memoryTypes.ts";

// ---------------------------------------------------------------------------
// extractAndApply
// ---------------------------------------------------------------------------

/**
 * Run background memory consolidation over a dialogue slice, with
 * deduplication and conflict handling.
 *
 * @param apiKey   Gemini API key (forwarded to processConversationSlice)
 * @param history  Dialogue history [{role, text}]
 * @param store    MemoryStore instance (injectable for testing)
 * @returns Updated full memory list, or null if no changes were made.
 */
export async function extractAndApply(
  apiKey: string,
  history: { role: string; text: string }[],
  store: MemoryStore = memoryStore,
): Promise<EnhancedMemory[] | null> {
  // Step 1: Run Gemini extraction to get raw MemoryTransaction[]
  // processConversationSlice handles its own isConsolidating lock.
  const updated = await processConversationSlice(apiKey, history);
  if (!updated) {
    // No changes generated by the model, or lock was busy
    return null;
  }

  // processConversationSlice already persisted the changes to disk.
  // We now need to reload what it saved, apply deduplication on any ADD
  // transactions it created, and re-save if deduplication caused further changes.
  //
  // Strategy:
  //   - Load current state from disk (which now includes the model's adds/updates)
  //   - Run a deduplication pass to merge/consolidate any duplicates introduced
  //   - If anything changed, save again and return the final array.

  store.clearCache(); // Ensure we read the model's fresh output from disk
  const current = await store.load();

  // Deduplication pass: look for pairs of active memories in the same category
  // that are similar to each other. If found, merge or flag as needs_revalidation.
  let changed = false;
  const result: EnhancedMemory[] = [...current];
  const processedIds = new Set<string>();

  for (let i = 0; i < result.length; i++) {
    const candidate = result[i];
    if (processedIds.has(candidate.id)) continue;
    if (candidate.status === "archived") continue;

    // Build a search space excluding the candidate itself
    const others = result.filter(
      (m) => m.id !== candidate.id && !processedIds.has(m.id),
    );

    const dedup = findSimilar(others, {
      category: candidate.category,
      text: candidate.text,
      key: candidate.key,
    });

    if (dedup.match === "exact" && dedup.existing) {
      // Keep the older record (dedup.existing) and remove the candidate
      // (the candidate is the newly added duplicate)
      if (candidate.createdAt > dedup.existing.createdAt) {
        // candidate is newer — remove it
        result.splice(i, 1);
        i--;
        changed = true;
      }
      processedIds.add(dedup.existing.id);
    } else if (dedup.match === "similar" && dedup.existing) {
      // Merge: keep dedup.existing, update its text if needed
      const existingIdx = result.findIndex((m) => m.id === dedup.existing!.id);
      if (existingIdx !== -1) {
        const merged = mergeText(
          result[existingIdx].text,
          candidate.text,
          dedup.score,
        );
        if (merged !== result[existingIdx].text) {
          result[existingIdx] = {
            ...result[existingIdx],
            text: merged,
            updatedAt: MemoryStore.now(),
          };
          changed = true;
        }
        // Remove the candidate duplicate
        result.splice(i, 1);
        i--;
        changed = true;
      }
      processedIds.add(dedup.existing.id);
    } else if (dedup.match === "conflict" && dedup.existing) {
      // Conflict: keep both but:
      //   - mark the existing one as needs_revalidation
      //   - new candidate gets low confidence
      const existingIdx = result.findIndex((m) => m.id === dedup.existing!.id);
      if (existingIdx !== -1 && result[existingIdx].status === "active") {
        result[existingIdx] = {
          ...result[existingIdx],
          status: "needs_revalidation",
          updatedAt: MemoryStore.now(),
        };
        changed = true;
      }
      // Lower the candidate's confidence
      if (candidate.confidence !== "low") {
        result[i] = { ...candidate, confidence: "low" };
        changed = true;
      }
    }
  }

  if (changed) {
    await store.save(result);
    return result;
  }

  // Nothing changed by deduplication — return what processConversationSlice gave us
  // (still non-null, indicating memories were updated by the model)
  return current;
}

/**
 * Utility: create a new EnhancedMemory with sensible defaults.
 * Used by MemoryManager.createMemory() and HttpGateway routes.
 */
export function makeEnhancedMemory(
  data: {
    category: MemoryCategory;
    text: string;
    key?: string;
    source?: MemorySource;
    importance?: EnhancedMemory["importance"];
    confidence?: EnhancedMemory["confidence"];
    expiresAt?: string;
  },
): EnhancedMemory {
  const now = MemoryStore.now();
  return {
    id: MemoryStore.newId(),
    category: data.category,
    text: data.text,
    key: data.key,
    createdAt: now,
    updatedAt: now,
    importance: data.importance ?? "medium",
    confidence: data.confidence ?? "medium",
    source: data.source ?? "system_generated",
    status: "active",
    expiresAt: data.expiresAt,
  };
}
